config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  resources :students
  resources :schools, only: [:show, :index]

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :school
  belongs_to :student
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :clients, dependent: :destroy
  has_many :students, through: :clients

  validates :name, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_save { self.name = name.capitalize }

  has_many :clients, dependent: :destroy
  has_many :schools, through: :clients

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all.order('name ASC')
  end

  def show
    @school = School.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all.order('name ASC')
  end

  def new
    @schools = School.all
    @student = Student.new
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Student deleted successfully'
    redirect_to '/'
  end

  def edit
    @schools = School.all
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    redirect_to '/'
  end

  def create
    @schools = School.all
    @student = Student.new(student_params)
    if @student.save
      redirect_to '/'
    else
      flash[:alert] = 'Please review the information provided'
      render 'new'
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :school_id, school_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pelicanconnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= alert %>
<%= yield %>

</body>
</html>

app/views/schools/index.html.erb
<header>
  <h1 class="h3">Schools</h1>
</header>
<table class="table table-striped">
  <thead>
    <tr>
      <th>School</th>
    </tr>
  </thead>
  <tbody>
    <% @schools.each do |school| %>
    <tr>
      <td><%= link_to school.name, school_path(school) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', students_path %>

app/views/schools/show.html.erb
<header>
  <h1 class="h3">
    <%= @school.name %> Students
  </h1>
</header>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @school.students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= link_to "Delete #{student.name}", student_path(student), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', schools_path %>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :school %>
  <%= f.collection_select(:school_ids, @schools, :id, :name,{}, {multiple: true}) %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<section class="PelicanConnect Students">
  <header>
    <h1 class="h3">Students</h1>
  </header>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Schools</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%if @students.any? %>
      <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td>
          <%student.schools.each do |school| %>
          <%= school.name%>
          <% end %>
        </td>
        <td><%= link_to "Delete #{student.name}", student_path(student), method: :delete %></td>
        <td><%= link_to "Edit #{student.name}", edit_student_path(student)%></td>
      </tr>
      <% end %>
      <% else %>
      <h1 class='h3'>No students to show</h1>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add a student', new_student_path %><br />
  <%= link_to 'View schools', schools_path %>
</section>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>
<br />
To select more than one school please press cmd while selecting schools
<br />
<%= link_to 'Back', students_path %>